Select * 
From nyc_sales

-- WANT TO KNOW HOW MANY PROPERTIES WERE SOLD IN HARLEM 

Select NEIGHBORHOOD,SUM(SALE_PRICE) AS TOTAL
from nyc_sales
WHERE NEIGHBORHOOD LIKE '%HARLEM%'
GROUP BY 1

-- SALES BY NEIGHBORHOOD

SELECT BOROUGH,NEIGHBORHOOD,SUM(SALE_PRICE) AS TOTAL_SALES,
CASE
		WHEN BOROUGH = 1 THEN 'MANHATTAN'
        WHEN BOROUGH = 2 THEN 'BRONX'
        WHEN BOROUGH = 3 THEN 'BROOKLYN'
        WHEN BOROUGH = 4 THEN 'QUEENS'
        WHEN BOROUGH = 5 THEN 'STATEN_ISLAND'
	END AS NYC_BOROUGH
FROM nyc_sales
GROUP BY 1,2
ORDER BY TOTAL_SALES DESC

-- TOTAL SALES PER BOROUGH

Select BOROUGH,SALE_DATE,SUM(SALE_PRICE) AS TOTAL_PRICE,
CASE
		WHEN BOROUGH = 1 THEN 'MANHATTAN'
        WHEN BOROUGH = 2 THEN 'BRONX'
        WHEN BOROUGH = 3 THEN 'BROOKLYN'
        WHEN BOROUGH = 4 THEN 'QUEENS'
        WHEN BOROUGH = 5 THEN 'STATEN_ISLAND'
	END AS NYC_BOROUGH
FROM nyc_sales
GROUP BY 1,2
ORDER BY NYC_BOROUGH


-- PORPERTIES LISTED
SELECT COUNT(BOROUGH) as PROPETIES_LISTED,
CASE
		WHEN BOROUGH = 1 THEN 'MANHATTAN'
        WHEN BOROUGH = 2 THEN 'BRONX'
        WHEN BOROUGH = 3 THEN 'BROOKLYN'
        WHEN BOROUGH = 4 THEN 'QUEENS'
        WHEN BOROUGH = 5 THEN 'STATEN_ISLAND'
	END AS NYC_BOROUGH
FROM nyc_sales
GROUP BY NYC_BOROUGH
ORDER BY NYC_BOROUGH



-- Shows which properties were sold and not sold 

Select SALE_PRICE,
CASE
		WHEN BOROUGH = 1 THEN 'MANHATTAN'
        WHEN BOROUGH = 2 THEN 'BRONX'
        WHEN BOROUGH = 3 THEN 'BROOKLYN'
        WHEN BOROUGH = 4 THEN 'QUEENS'
        WHEN BOROUGH = 5 THEN 'STATEN_ISLAND'
	END AS NYC_BOROUGH,
CASE
	WHEN SALE_PRICE >1000 THEN 'SOLD'
    WHEN SALE_PRICE <=1000 THEN 'NOT SOLD'
    END AS SOLD_PROPERTIES
FROM nyc_sales

